# Generated by Django 3.2.4 on 2021-12-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
