# Generated by Django 3.2.4 on 2021-11-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_catagory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
