# Generated by Django 3.2.4 on 2021-11-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='webiste',
        ),
    ]
