# Generated by Django 3.2.4 on 2022-05-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_status',
            field=models.CharField(choices=[('pub', 'Publish'), ('dra', 'DRAFT'), ('pri', 'Private')], default='dra', max_length=3),
        ),
    ]
