# Generated by Django 3.2.4 on 2022-05-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_publish_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
    ]
