# Generated by Django 3.2.4 on 2022-05-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.CharField(help_text='Headline of the article', max_length=240),
        ),
    ]
