# Generated by Django 3.2.4 on 2021-07-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtest',
            name='user1',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubTest',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
