# Generated by Django 3.2.4 on 2022-04-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210727_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
