# Generated by Django 3.2.4 on 2022-04-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220413_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
