# Generated by Django 3.2.4 on 2022-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
