# Generated by Django 3.2.4 on 2022-05-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_user_id_number'),
        ('account', '0006_profile_auth_token'),
    ]

    operations = [
    ]
