# Generated by Django 3.2.4 on 2022-04-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_rename_catagory_purchasing_plan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasing',
            old_name='mobile_banking_name',
            new_name='banking_name',
        ),
    ]
