# Generated by Django 3.2.4 on 2022-04-11 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20220411_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='plan_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.plan_category'),
        ),
    ]
