# Generated by Django 3.2.4 on 2022-04-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_alter_purchasing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
