# Generated by Django 3.2.4 on 2022-04-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_alter_purchasing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
