# Generated by Django 3.2.4 on 2022-04-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_alter_purchasing_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasing',
            old_name='name',
            new_name='user_name',
        ),
    ]
