# Generated by Django 3.2.4 on 2022-04-14 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_user_id_number'),
        ('pricing', '0012_purchasing_how_much_you_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasing',
            name='profi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
