# Generated by Django 3.1.7 on 2021-04-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='lasttitle',
            field=models.CharField(default=1, max_length=264),
            preserve_default=False,
        ),
    ]
