# Generated by Django 3.1.7 on 2021-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=264)),
                ('text1', models.TextField(max_length=1000)),
                ('text2', models.TextField(max_length=1000)),
            ],
        ),
    ]
