# Generated by Django 3.1.7 on 2021-04-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
