# Generated by Django 3.1.7 on 2021-04-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_testimonial1_testimonial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=264)),
                ('text1', models.TextField(max_length=1000)),
                ('text2', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('text', models.TextField(max_length=500)),
                ('img1', models.ImageField(upload_to='clients/')),
                ('img2', models.ImageField(upload_to='clients/')),
                ('img3', models.ImageField(upload_to='clients/')),
                ('img4', models.ImageField(upload_to='clients/')),
                ('img5', models.ImageField(upload_to='clients/')),
                ('img6', models.ImageField(upload_to='clients/')),
                ('img7', models.ImageField(upload_to='clients/')),
                ('img8', models.ImageField(upload_to='clients/')),
                ('img9', models.ImageField(upload_to='clients/')),
                ('img10', models.ImageField(upload_to='clients/')),
            ],
        ),
    ]
