# Generated by Django 3.2.4 on 2022-05-23 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264, null=True)),
                ('image', models.ImageField(upload_to='clients')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.client_image'),
        ),
    ]
