# Generated by Django 3.2.4 on 2022-05-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_client_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_image',
        ),
        migrations.AddField(
            model_name='client',
            name='client_image',
            field=models.ManyToManyField(blank=True, null=True, to='about.Client_image'),
        ),
    ]
