# Generated by Django 3.2.4 on 2022-05-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20220523_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img10',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img7',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img8',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img9',
        ),
    ]
