# Generated by Django 3.1.7 on 2021-04-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_header',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
