# Generated by Django 3.1.7 on 2021-04-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_auto_20210415_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_footer4',
            name='copy_right',
            field=models.CharField(max_length=30),
        ),
    ]
