# Generated by Django 3.2.4 on 2021-07-26 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_category_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Project_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
