# Generated by Django 3.2.4 on 2022-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210726_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_image',
            field=models.ManyToManyField(to='portfolio.Portfolio_image'),
        ),
    ]
