# Generated by Django 3.2.4 on 2022-06-05 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_image',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.portfolio'),
        ),
    ]
