# Generated by Django 3.2.4 on 2022-06-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_portfolio_image_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio_image',
        ),
    ]
